// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAovBfCU-tH6fOlBGP17Czuh69h5GfM594',
    appId: '1:756814622033:web:fc90bff4d01aac6c4f7770',
    messagingSenderId: '756814622033',
    projectId: 'safezone-44dd0',
    authDomain: 'safezone-44dd0.firebaseapp.com',
    databaseURL: 'https://safezone-44dd0-default-rtdb.firebaseio.com',
    storageBucket: 'safezone-44dd0.firebasestorage.app',
    measurementId: 'G-7V634KC2VY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoH5ogGzrOWfgVzX8YDYxI3z7nOyLSZY8',
    appId: '1:756814622033:android:bc75184d3ea6af874f7770',
    messagingSenderId: '756814622033',
    projectId: 'safezone-44dd0',
    databaseURL: 'https://safezone-44dd0-default-rtdb.firebaseio.com',
    storageBucket: 'safezone-44dd0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoqV0UX9k7r4UrtNUMNb_Py__q1T_ywqo',
    appId: '1:756814622033:ios:f2e060eab927f28e4f7770',
    messagingSenderId: '756814622033',
    projectId: 'safezone-44dd0',
    databaseURL: 'https://safezone-44dd0-default-rtdb.firebaseio.com',
    storageBucket: 'safezone-44dd0.firebasestorage.app',
    androidClientId: '756814622033-m841tgaoph1ib4b2gqljhv7bbif9c57s.apps.googleusercontent.com',
    iosClientId: '756814622033-knvqjj49miifq452am1vh52sdv2u7ulu.apps.googleusercontent.com',
    iosBundleId: 'com.example.safezone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoqV0UX9k7r4UrtNUMNb_Py__q1T_ywqo',
    appId: '1:756814622033:ios:f2e060eab927f28e4f7770',
    messagingSenderId: '756814622033',
    projectId: 'safezone-44dd0',
    databaseURL: 'https://safezone-44dd0-default-rtdb.firebaseio.com',
    storageBucket: 'safezone-44dd0.firebasestorage.app',
    androidClientId: '756814622033-m841tgaoph1ib4b2gqljhv7bbif9c57s.apps.googleusercontent.com',
    iosClientId: '756814622033-knvqjj49miifq452am1vh52sdv2u7ulu.apps.googleusercontent.com',
    iosBundleId: 'com.example.safezone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAovBfCU-tH6fOlBGP17Czuh69h5GfM594',
    appId: '1:756814622033:web:66da957927d293964f7770',
    messagingSenderId: '756814622033',
    projectId: 'safezone-44dd0',
    authDomain: 'safezone-44dd0.firebaseapp.com',
    databaseURL: 'https://safezone-44dd0-default-rtdb.firebaseio.com',
    storageBucket: 'safezone-44dd0.firebasestorage.app',
    measurementId: 'G-GKHWF9QTRS',
  );
}
